version: '3.1'

services:

  mariadb:
    image: mariadb:10.6.7-focal
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - ${DOCKER_MARIADB_PORT}:3306
    volumes:
      - ${DOCKER_MARIADB_VOLUME}:/var/lib/mysql

networks:
  default:
    external:
      name: "docker-lan"
